# -----------------------------------------------------
# Asanagi Umi Theme - Hyprland Config
# -----------------------------------------------------

general {
    gaps_in = 5
    gaps_out = 12
    border_size = 2
    col.active_border = rgb(a855f7) rgb(f43f5e) 45deg
    col.inactive_border = rgba(3b1d5caa)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 12
    active_opacity = 0.96
    inactive_opacity = 0.88
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
        noise = 0.015
        contrast = 1.1
        brightness = 0.95
    }

    shadow {
        enabled = true
        range = 24
        render_power = 3
        color = rgba(08030dbb)
        color_inactive = rgba(08030d55)
    }
}

animations {
    enabled = true
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.65, 0, 0.35, 1
    bezier = linear, 0, 0, 1, 1
    bezier = almostLinear, 0.5, 0.5, 0.75, 1.0
    bezier = quick, 0.15, 0, 0.1, 1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 2.5, linear, popin 87%
    animation = fadeIn, 1, 2.5, almostLinear
    animation = fadeOut, 1, 2.5, almostLinear
    animation = fade, 1, 3.03, quick
    animation = workspaces, 1, 4.0, easeOutQuint, slide
}
