# -----------------------------------------------------
# Asanagi Umi Theme - Ultra Minimalist Starship Prompt
# -----------------------------------------------------

format = "$directory$git_branch$git_status$character"

[directory]
style = "bold #a855f7"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
style = "#818cf8"
symbol = ""
format = "on [$branch]($style) "

[git_status]
style = "#f43f6e"
format = "[$all_status$ahead_behind]($style)"

[character]
success_symbol = "[❯](bold #a855f7)"
error_symbol = "[❯](bold #f43f6e)"
